### PR TITLE
feat: Add container support

### PR DESCRIPTION
**Pull request by Romakita**
- ServerSettingsService can be overriden,
- InjectorService use container,
- Deprecate all static method on InjectorService,
- Allow multiple server instance.

@milewski Can you test this branch with your project? pls? I need some feedback before continuing the latest refactoring (and publish the v5). Thanks ;)

### CODE REVIEW

**Comment by milewski** [comment]
Apparently all my tests are still green with this branch 👍

**Comment by milewski** [comment]
only one weird thing start happening trough, one of my utility class wasn't outputting all these logs before

```
npm run db:seed

> yumi-backend@0.0.0-development db:seed G:\Code\yumi-frontend\backend
> ts-node source/database/Command.ts

[2018-05-30T17:05:34.866] [INFO ] [TSED] - settings.rootDir => G:/Code/yumi-frontend/backend/source
[2018-05-30T17:05:34.869] [INFO ] [TSED] - settings.env => development
[2018-05-30T17:05:34.870] [INFO ] [TSED] - settings.httpPort => 9000
[2018-05-30T17:05:34.871] [INFO ] [TSED] - settings.httpsPort => 8000
[2018-05-30T17:05:34.871] [INFO ] [TSED] - settings.version => 1.0.0
[2018-05-30T17:05:34.871] [INFO ] [TSED] - settings.uploadDir => G:/Code/yumi-frontend/backend/source/uploads
[2018-05-30T17:05:34.872] [INFO ] [TSED] - settings.debug => false
[2018-05-30T17:05:34.872] [INFO ] [TSED] - settings.scope => singleton
[2018-05-30T17:05:34.873] [INFO ] [TSED] - settings.logger => { logRequest: true, jsonIndentation: 2 }
[2018-05-30T17:05:34.874] [INFO ] [TSED] - settings.mount => { '/v1': 'G:/Code/yumi-frontend/backend/source/controllers/**/*.ts' }
[2018-05-30T17:05:34.875] [INFO ] [TSED] - settings.exclude => [ '**/*.spec.ts', '**/*.spec.js' ]
[2018-05-30T17:05:34.875] [INFO ] [TSED] - settings.componentsScan => [ 'G:/Code/yumi-frontend/backend/source/services/**/**.ts',
  'G:/Code/yumi-frontend/backend/source/middlewares/**/**.ts' ]
[2018-05-30T17:05:34.876] [INFO ] [TSED] - settings.acceptMimes => [ 'application/json' ]
[2018-05-30T17:05:34.876] [INFO ] [TSED] - settings.host => localhost
[2018-05-30T17:05:34.876] [INFO ] [TSED] - settings.serveStatic => { '/v1/auth/wechat/': 'G:/Code/yumi-frontend/backend/source/static',
  '/': 'G:/Code/yumi-frontend/backend/distribution/static' }
[2018-05-30T17:05:34.877] [INFO ] [TSED] - settings.ajv => { errorFormat: [Function: errorFormat],
  options: { verbose: false } }
[2018-05-30T17:05:34.877] [INFO ] [TSED] - settings.mongoose => { url: 'mongodb://localhost:27017/yumi', connectionOptions: {} }
[2018-05-30T17:05:34.877] [INFO ] [TSED] - settings.swagger => { path: '/documentation' }
[2018-05-30T17:05:34.877] [INFO ] [TSED] - Build services
[2018-05-30T17:05:36.079] [INFO ] [TSED] - Map controllers
[2018-05-30T17:05:36.083] [INFO ] [TSED] - Routes mounted :
[2018-05-30T17:05:36.092] [INFO ] [TSED] - 
┌────────────────┬────────────────────────────────────┬──────────

+300 Lines showing all the api endpoints....

───────────────────────────────────┘
[2018-05-30T17:05:36.181] [INFO ] [TSED] - Started in 11549 ms
RoleTableSeeder Seeded!
PlanTableSeeder Seeded!
UserTableSeeder Seeded!
Seeder Completed.
```

previously it wasn't outputting all these logs as when i start the server...

**Comment by Romakita** [comment]
Thanks a lot @milewski 
I'd just updated the branch to fix your problem. You can try again ;)

**Comment by milewski** [comment]
i might be doing something wrong.... but after pulling the latest i am getting this now:

```
"C:\Program Files\nodejs\node.exe" G:\Code\yumi-frontend\backend\node_modules\mocha\bin\_mocha --require ts-node/register --no-timeouts --exit --ui bdd --reporter "C:\Program Files\JetBrains\PhpStorm 2018.1.3\plugins\NodeJS\js\mocha-intellij\lib\mochaIntellijReporter.js" test\api\**\*.ts

G:\Code\ts-express-decorators\dist\packages\src\common\filters\services\FilterService.ts:14
export class FilterService extends ProxyMap<Type<any> | any, Provider<any>> {
                                   ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (G:\Code\ts-express-decorators\dist\packages\src\common\filters\services\FilterService.ts:14:36)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Code\ts-express-decorators\dist\packages\src\common\filters\index.ts:22:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Code\ts-express-decorators\dist\packages\src\common\index.ts:6:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\Code\yumi-frontend\backend\test\api\admin\AdminPlanController.ts:3:18)
    at Module._compile (module.js:660:30)
    at Module.m._compile (G:\Code\yumi-frontend\backend\node_modules\ts-node\src\index.ts:403:23)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .ts] (G:\Code\yumi-frontend\backend\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at G:\Code\yumi-frontend\backend\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (G:\Code\yumi-frontend\backend\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (G:\Code\yumi-frontend\backend\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (G:\Code\yumi-frontend\backend\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

Process finished with exit code 1

```

**Pull request merged**
