### PR TITLE
Add Prettier Integration

### PR DESCRIPTION
**Pull request by milewski**
I haven't "applied it" yet... cuz this will trigger a change in every single file... so im chunking it down into small changes before applying it. have a look see if you agree with the rules :)

### CODE REVIEW

**Comment by milewski** [comment]
https://github.com/Romakita/ts-express-decorators/issues/360

**Comment by milewski** [comment]
i have added them back

**Comment by Romakita** [comment]
@troyanskiy I'm ok for `tabindent: 2`. I'd just updated the branch. I removed the rules to lint js, md and json. Isn't necessary :)

After merging, @milewski you can finish the branch ;)
```
git fetch
git reset --hard origin/add_prettier_integration
gflow finish
```

See you,
Romain

**Comment by Romakita** [comment]
I finished this branch ;)

**Comment by Romakita** [comment]
Master branch is just for the PR. gflow => rebase, test, and merge branch with `production`.
I don't want merge a PR directly in production ;)

**Comment by milewski** [comment]
oh i see.. i will start learning glfow 👍

**Comment by Romakita** [comment]
No problem ;)

**Pull request merged**
