### PR TITLE
Fixed required field name when setting a name with @JsonProperty

### LINKED ISSUE #396: [Bug] Wrong required field name when naming field in JSON property
## Informations

Type | Version
---|---
Bug | 4.23.1

****

## Description
I am working on documenting my models and I am using a different name in the generated swagger and the code like this:
```typescript
export default class MyEntity {
	@Required()
	@JsonProperty('my_field')
	myField: string;
}
```
The generated YAML:
```yaml
definitions:
  MyEntity:
    properties:
      my_field:
        type: string
    required:
      - myField # <-- This should be "my_field"
```

## Acceptance criterias
- [ ] Ts.ED version (bug)

### PR DESCRIPTION
**Pull request by TomerAmirV**
## Informations

Type | Migration
---|---
Fix|No

****

## Description
closes #396 

## Todos

- [ ] Tests
- [ ] Coverage
- [ ] Example
- [ ] Documentation

### CODE REVIEW

**Comment by TomerAmirV** [comment]
sorry for indentation changes... I can fix them if you want 😅

**Comment by Romakita** [comment]
No problem but your PR is in conflict, apparently :)

**Comment by TomerAmirV** [comment]
Hi @Romakita 
What conflict? github shows "This branch has no conflicts with the base branch"
I'll be happy to fix

**Comment by Romakita** [comment]
Ok Because I use the rebase options. It's merged ;) Thanks @TomerAmirV 
The release is 4.23.2

See you

**Comment by TomerAmirV** [comment]
Thanks @Romakita !
Happy to help 😄

**Pull request merged**
