### PR TITLE
feat: Create custom error with headers and errors field.

### PR DESCRIPTION
**Pull request by Romakita**
Introduce a new interface IResponseError which allow to create custom
error based on BadRequest, NotFound, etc... When a custom error implement
this interface and fill the headers or errors fields, these information will
be forwarded to the GlobalErrorHandler and will be used to generate the
 response headers (errors generate the header `errors = "[]"` formatted in JSON).

- fix swagger documentation with `@Any` decorator.

Closes: #367

### CODE REVIEW

**Comment by Romakita** [comment]
@kalu111 effectively, the error management on Socket isn't implemented. It should do the same things. 

Customized name for errors field? why not. It's just a key configuration in server settings.

**Comment by Romakita** [comment]
@kalu111 Socket doesn't define a format to send error. This is why I haven't implemented a global error handler for the socket. With the UseSocketAfter decorator on your class, you can handle all error and implement your own error handler strategy, right ?

**Comment by kalu111** [comment]
@Romakita Yes, You have right about socket error handling.
In my applications I have implemented error handling by using `@SocketMiddlewareError()`.

Thanks,
Bye.

**Comment by Romakita** [comment]
But we can use your Middleware Error as example :)

**Pull request merged**
