### PR TITLE
fix(tsc): Fix typescript compilation error

### PR DESCRIPTION
**Pull request by Romakita**

### CODE REVIEW

**Comment by Romakita** [comment]
@milewski if you want try gflow it's a good time for you ;)
Merge this PR. Then:
```
npm install -g gflow
```
Then checkout this branch on your local. And to finish `gflow finish`. 
And enjoy !
Romain :)

**Comment by milewski** [comment]
Worked :D

**Comment by Romakita** [comment]
Now you are a master of deployment for this project :p

**Pull request merged**
