### PR TITLE
feat(mvc,di): Scope on Service, Controller and Middleware

### PR DESCRIPTION
**Pull request by Romakita**
## Informations

Type | Status | Migration
---|---|---
Feature | Ready | No

****

## Description
The [@Scope](docs/api/common/mvc/scope) change the behavior of a [Provider](docs/api/common/di/provider.md) like a Service, Controller or Middleware.

All providers are created one time when the server initialisation (Singleton pattern).

But [@Scope](docs/api/common/mvc/scope) decorator change that. It's mean, your Service, Controller or Middleware will be 
created each time according to the scope configuration. Actually, the only scope supported is `request`. 
So for each incoming request, a new instance of the provider will be created.

## Example

This example is available for Middleware and Controller.

```typescript
@Middleware()
@Scope("request" || ProviderScope.REQUEST) 
export class TokenMiddleware implements IMiddleware {
    // Inject service into middleware
    constructor(public userDetailsService: UserDetailsService) { }

    use(@Request() request: Express.Request,
        @EndpointInfo() endpoint: Endpoint,
        @Response() response: Express.Response,
        @Next() next: Express.NextFunction) {
        ...
        this.userDetailsService.profile = user;
        ...
    }
}
```
> In this case, the TokenMiddleware will created for each new request.

## With a Service

For the Service, it's almost the case of the previous example, but you need to keep in mind this point:

!> `@Scope` on service work only if the provider that uses it's annotated by `@Scope` decorator too.

```typescript
@Service()
@Scope("request") 
export class UserDetailsService {
   ...
}

@Middleware()
@Scope("request") // (1)
export class TokenMiddleware implements IMiddleware {
    // Inject service into middleware
    constructor(public userDetailsService: UserDetailsService) { }

    use(@Request() request: Express.Request,
        @EndpointInfo() endpoint: Endpoint,
        @Response() response: Express.Response,
        @Next() next: Express.NextFunction) {
        ...
        this.userDetailsService.profile = user;
        ...
    }
}
```
!> <sup>(1)</sup> Leaving out `@Scope("request")` on `TokenMiddleware` will give an [InjectionScopeError](api/common/di/injectionscopeerror.md).

## Todos

- [x] Tests
- [x] Coverage
- [x] Example
- [x] Documentation

### CODE REVIEW

**Comment by Romakita** [comment]
#58

**Comment by nicojs** [comment]
What strings will be possible using `@Scope('string')`. Only 'request' and 'singleton'? If so, why not make it an enum? Or use `@RequestScoped() ` vs `@SingletonScoped()`

**Comment by Romakita** [comment]
Actually the possible value is "request" or false. By default, it's always a singleton. If you use Scope() without parameters, the default value is "request".

I actually do not think about creating an enum, but I can add this, even though I think it's not mandatory.

Create two decorators will not maintainable in the future, if we add new options.

**Comment by nicojs** [comment]
> Actually the possible value is "request" or false. By default, it's always a singleton. If you use Scope() without parameters, the default value is "request".

I personally would like to see it more explicit. With an enum I cannot make the mistake of misspelling `'request'`. It's also directly visible what values are possible. I also think the meaning of `@Scope(false)` and `@Scope()` is not directly clear.

**Comment by Romakita** [comment]
Yes I agree ;)

**Comment by Romakita** [comment]
@nicojs down :)

**Comment by nicojs** [comment]
Awesome! You work fast :racehorse:

**Pull request merged**
