### PR TITLE
fix(mvc): Fix allow when Required and Allow are used at the same time

### PR DESCRIPTION
**Pull request by Romakita**
Closes: #348

### CODE REVIEW

**Comment by Romakita** [comment]
Now this fix will work @milewski ;)
Thanks for your help (with the mongoose documentation)

**Comment by milewski** [comment]
still not working :( got the same error.. and have found some other "blockers" related to this issue on the way... 

```ts
export class UserModel {

    @Indexed()
    @Required()
    @Email()
    @Unique()
    @Allow(null)
    email: string

    @Required()
    @Minimum(6)
    @Allow(null)
    password: string

}

/// on my tests

const userData = {
    email: null,
    password: null
}

await this.agent.post('/v1/user/create').send(userData)


/// on the controller

@Post('/user/create')
@Status(201)
async createUser(@BodyParams() userData: UserModel) { 
     await this.userService.create(userData)
}

// error 
@Email() fail because null is not a email
@Minimum(6) fail because null is not minimum 6

email:string, password: string, fails because null is not a string

```

and disabling these checks and letting the request hit the user service still gets

```users validation failed: password: Path `password` is required., email: Path `email` is required.```

**Comment by Romakita** [comment]
@milewski Ok I'll try your example and fix it. Tell me If you find others problems :)

**Comment by Romakita** [comment]
Work fine now. Just one point, in your example replace `Minimum` by `MinLength` ;).

See you

**Pull request merged**
